version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password

